global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'devops-demo-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['32.199.96.184:30082']  # Replace with the actual NodePort of your application service