apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
        - name: devops-demo-app
          image: devops-demo-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: "172.17.0.1"
            - name: DB_USER
              value: "appuser"
            - name: DB_PASS
              value: "apppassword"
          ports:
            - containerPort: 8080
