apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-service
  template:
    metadata:
      labels:
        app: person-service
    spec:
      containers:
        - name: person-service
          image: person-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_NAME
              value: "devopsdb"
            - name: DB_USER
              value: "appuser"
            - name: DB_PASS
              value: "apppassword"
          ports:
            - containerPort: 8082
